### ISSUE TITLE
PyDirectInteraction.mouse_down() got an unexpected keyword argument 'key'

### ISSUE THREAD

**Issue by qhhuang** [ok-oldking/ok-script#4]
PyDirectInteraction.py
line115 修改为
    def mouse_down(self, x=-1, y=-1, name=None, key=None):
line125 修改为
    def mouse_up(self, key=None):

**Comment by ok-oldking** [comment]
PyDirectInteraction可能有些不支持, 你有fork的话提个pr看看吧
